<a href="https://colab.research.google.com/github/rhysdavies21/library/blob/master/linear_algebra_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear algebra functions

In [0]:
import numpy as np

In [41]:
# Re-shaping
print('Original')
x = np.array([[0.,1.],[2.,3.],[4.,5.]])
print('Shape of x: ', x.shape)
print('Type of x: ', type(x))
display('x: ', x)

print('\nRe-shaped')
y = x.reshape((2,3))
print('Shape of y: ', y.shape)
print('Type of y: ', type(y))
display('y: ', y)

Original
Shape of x:  (3, 2)
Type of x:  <class 'numpy.ndarray'>


'x: '

array([[0., 1.],
       [2., 3.],
       [4., 5.]])


Re-shaped
Shape of y:  (2, 3)
Type of y:  <class 'numpy.ndarray'>


'y: '

array([[0., 1., 2.],
       [3., 4., 5.]])

In [42]:
# Numpy transpose
q = np.zeros((300,20))
print('Shape of array: ', q.shape)
w = np.transpose(q)
print('Shape of transpose: ', q.shape)

Shape of array:  (300, 20)
Shape of transpose:  (300, 20)


In [43]:
# Element-wise relu
def naive_relu(x):
  assert len(x.shape) == 2
  
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)
  return x

a = np.array([[0.,-1.,6.],[2.,-3.,7.],[-4.,5.,-55]])
naive_relu(a)

array([[0., 0., 6.],
       [2., 0., 7.],
       [0., 5., 0.]])

In [44]:
# Element-wise addition
def naive_add(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
  return x

u = np.array([[0.,-1.,6.],[2.,3.,7.],[-4.,5.,-55]])
v = np.array([[0.,-1.,6.],[2.,3.,7.],[-4.,5.,-55]])
naive_add(u,v)

array([[   0.,   -2.,   12.],
       [   4.,    6.,   14.],
       [  -8.,   10., -110.]])

In [45]:
# Broadcasting - adding matrix and vector
def naive_add_matrix_and_Vector(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[j]
  return x
  
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
print('a')
display(a)
print('\nb')
display(b)
print('\nadd_matrix_vector')
naive_add_matrix_and_Vector(a,b)

a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


b


array([1, 2, 3])


add_matrix_vector


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [46]:
# Tensor dot 
def naive_vector_dot(x,y):
  assert len(x.shape) == 1
  assert len(y.shape) == 1
  assert x.shape[0] == y.shape[0]

  z = 0 
  for i in range(x.shape[0]):
    z+= x[i] * y[i]
  return z

a = np.array([1,2,3])
b = np.array([2,4,6])
naive_vector_dot(a,b)

28

In [47]:
# Matrix vector dot
def naive_matrix_vector_dot(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 1
  assert x.shape[1] == y.shape[0]

  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i,j] * y[j]
  return z

a = np.array([[1,2,3],[4,5,6]])
b = np.array([2,4,6])
naive_matrix_vector_dot(a,b)

array([28., 64.])

In [48]:
# Matrix multiplication
def naive_matrix(x,y):
  assert len(x.shape) == 2
  assert len(y.shape) == 2
  assert x.shape[1] == y.shape[0]

  z = np.zeros((x.shape[0],y.shape[1]))
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i,:]
      column_y = y[:,j]
      z[i,j] = naive_vector_dot(row_x, column_y)
  return z
  
a = np.array([[1,2,3],[4,5,6],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[4,5,6]])
naive_matrix(a,b)

array([[21., 27., 33.],
       [48., 63., 78.],
       [48., 63., 78.]])